
import React from 'react';
import { Resource, Category } from '../types';
import { ResourceCard } from './ResourceCard';

interface HomeProps {
  onNavigate: (view: string) => void;
  resources: Resource[];
}

export const Home: React.FC<HomeProps> = ({ onNavigate, resources }) => {
  const influentialResources = resources.filter(r => r.category === Category.INFLUENTIAL);

  return (
    <div>
      {/* Hero Section */}
      <div className="max-w-4xl mx-auto px-4 pt-12 pb-8 sm:pt-20 sm:pb-16 text-center">
        <h1 className="text-4xl sm:text-6xl font-extrabold text-slate-900 tracking-tight mb-6">
          A Global Community for <br/>
          <span className="text-academic-600">Image-Based Profiling</span>
        </h1>
        <p className="text-xl text-slate-600 mb-8 max-w-2xl mx-auto">
          Uniting researchers, data scientists, and biologists worldwide to advance the field of single-cell morphological analysis.
        </p>
        <div className="flex flex-col sm:flex-row gap-4 justify-center">
          <button 
            onClick={() => onNavigate('resources')}
            className="px-8 py-4 bg-academic-600 text-white rounded-lg font-bold shadow-lg hover:bg-academic-700 transition-transform transform hover:-translate-y-1"
          >
            <i className="fa-solid fa-magnifying-glass mr-2"></i>
            Explore Resources
          </button>
          <button 
            onClick={() => onNavigate('about')}
            className="px-8 py-4 bg-white text-slate-700 border border-slate-200 rounded-lg font-bold shadow hover:bg-slate-50 transition-colors"
          >
            Join Community
          </button>
        </div>
      </div>

      {/* Motivation / Community Section */}
      <div className="max-w-6xl mx-auto px-4 mb-20">
        <div className="bg-white rounded-2xl shadow-sm border border-slate-100 p-8 sm:p-12">
          <h2 className="text-2xl font-bold text-slate-900 mb-4">Who We Are</h2>
          <p className="text-slate-600 leading-relaxed mb-6">
            CytoData is more than just a collection of tools; it is a vibrant, global ecosystem of scientists dedicated to understanding biology through images.
            By extracting thousands of features from individual cells, our community creates phenotypic profiles that serve as "fingerprints" for genetic perturbations and drug treatments. 
            Together, we are revolutionizing functional genomics and drug discovery through open collaboration.
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mt-8">
              <div 
                onClick={() => onNavigate('datasets')}
                className="p-6 bg-slate-50 rounded-xl border border-slate-100 hover:border-academic-500 hover:shadow-md transition-all cursor-pointer group"
              >
                  <i className="fa-solid fa-users-viewfinder text-academic-500 text-3xl mb-3 group-hover:scale-110 transition-transform"></i>
                  <h3 className="font-bold text-lg text-slate-900 mb-1">Shared Data</h3>
                  <p className="text-sm text-slate-500">Access massive public datasets generated by the community.</p>
              </div>
              <div 
                onClick={() => onNavigate('software')}
                className="p-6 bg-slate-50 rounded-xl border border-slate-100 hover:border-academic-500 hover:shadow-md transition-all cursor-pointer group"
              >
                  <i className="fa-solid fa-laptop-code text-academic-500 text-3xl mb-3 group-hover:scale-110 transition-transform"></i>
                  <h3 className="font-bold text-lg text-slate-900 mb-1">Collaborative Tools</h3>
                  <p className="text-sm text-slate-500">Discover open-source pipelines maintained by experts worldwide.</p>
              </div>
          </div>
        </div>
      </div>

      {/* Influential Papers Section */}
      <div className="bg-slate-50 border-t border-slate-200 py-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <div className="inline-flex items-center justify-center w-12 h-12 rounded-full bg-white border border-slate-200 text-academic-500 mb-4 shadow-sm">
                <i className="fa-solid fa-crown text-2xl"></i>
            </div>
            <h2 className="text-3xl font-extrabold text-slate-900 mb-4">Foundational Research</h2>
            <p className="max-w-2xl mx-auto text-lg text-slate-600">
              Essential reading for anyone joining the field, selected by the CytoData community.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {influentialResources.map(resource => (
              <ResourceCard key={resource.id} resource={resource} />
            ))}
          </div>

          <div className="mt-12 text-center">
             <button 
                onClick={() => onNavigate('resources')}
                className="text-academic-600 font-semibold hover:text-academic-800 underline"
              >
                Browse all literature &rarr;
              </button>
          </div>
        </div>
      </div>
    </div>
  );
};